version: '3.9'

services:
  # login-api:
  #   build:
  #     context: ./Backend/Login API
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./Backend/Login API:/app:cached
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - app-network
  #   restart: always

  wordle-api:
    build:
      context: ./Backend/Wordle API
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./Backend/Wordle API:/app:cached
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=3306
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend/wordle-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/wordle-frontend:/app:cached
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling
      - CHOKIDAR_INTERVAL=500    # Optional: Poll every 500ms
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_WORDLE_API_URL=http://localhost:5001
    networks:
      - app-network
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
