# Use a lightweight Python image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . .


# Set environment variables for Flask development
ENV FLASK_APP=API/app.py
# This enables debug mode with hot-reloading
ENV FLASK_ENV=development  

# Install the required packages from requirements.txt
RUN pip install -r requirements.txt
WORKDIR /app

# Expose the port Flask will run on
EXPOSE 5000

# Command to run Uvicorn with Flask in development mode
CMD ["uvicorn", "app:asgi_app", "--host", "0.0.0.0", "--port", "5000", "--reload"]