# Use the official Python image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the app files to the container
COPY app.py ./
COPY requirements.txt ./

# Install required Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5001 for the container
EXPOSE 5001

# Run the app
CMD ["python", "app.py"]
