FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV FLASK_ENV=production
EXPOSE 5001
CMD ["uvicorn", "app:asgi_app", "--host", "0.0.0.0", "--port", "5001"]
