apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: TnIxdGVhY2hlcklzQmlnQm9zc01pa2FlbFN2YWhuYmVyZw==
  MYSQL_DB: d29yZGxlYmFzZQ==
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: TnIxdGVhY2hlcklzQmlnQm9zc01pa2FlbFN2YWhuYmVyZw==
