apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordle-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordle-frontend
  template:
    metadata:
      labels:
        app: wordle-frontend
    spec:
      containers:
        - name: wordle-frontend
          image: simlju0519/wordle-frontend:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: wordle-frontend
spec:
  selector:
    app: wordle-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
